[project]
name = "qr-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "weldymq", email = "asavch2007@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.3.0",
    "qrcode>=8.2",
]

[project.scripts]
qr-project = "qr_project:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
